version: '3'
services:

  node:
    build:
      dockerfile: ./dockerfile
      context: .
    container_name: missions_node
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    depends_on:
      - "database"

  database:
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trybestrelar
    ports:
    - "33060:3306"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql